// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Follower struct {
	ID           int64
	FollowerID   int64
	FollowedToID int64
}

type Tweet struct {
	ID              int64
	TweetText       string
	PostedByID      int64
	PublicationDate time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	LastName  string
	FirstName string
	Age       int32
}
